### ISSUE TITLE
Error: "Installation not found"

### ISSUE THREAD

**Issue by jwelrynewone** [snarkify/poseidon-circuit#8]
I tried to deploy test prover from template, but face the issue "Installation not found"

<img width="575" alt="Screenshot 2023-11-11 at 18 51 45" src="https://github.com/snarkify/poseidon-circuit/assets/107742812/6023f469-717d-4200-ae73-9fb18c1bd3b3">

**Comment by drouyang** [comment]
We just landed a backend fix that should fix this problem. Could you try again please?

The suspected causes was that the newly created destination repo was not returned by GitHub for whatever reason, which caused the subsequent git push to fail. We added some wait-and-retry logic to mitigate the problem. Please let us know if it’s working for you.

**Comment by ErdongChen61** [comment]
We've recently implemented a new update addressing the issue you experienced. The underlying problem stemmed from the GitHub API's default setting, which only displayed a maximum of 30 repositories. We've adjusted this limit to show more repositories, which should resolve the error. Please feel free to reach out if the issue persists.

Thank you for your patience!

**Comment by jwelrynewone** [comment]
Deploy Success: poseidon
